paths:
  raw_gt: "../data/gt.yml"          # Original ground truth
  raw_results: "../data/linemod_res.yml" # Original predictions
  ground_truth: "../data/gt_reformatted.yml"        # Formatted ground truth
  predictions: "../data/res_reformatted.yml" # Formatted results
  point_cloud: "../data/obj_01.ply"
  output_dir: "../results/"

format_inputs: True  # Set to False after first run

thresholds:
  rotation: [5, 10]       # Good/Bad thresholds in degrees
  translation: [0.01, 0.05] # In meters
  pose: [0.1, 0.3]        # Frobenius norm
  add: [0.01, 0.05]       # In meters